name: test

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
    contents: read
    actions: write

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: app
      run: |
        docker pull ghcr.io/dochimcifgi625fwxczwnjqow81a001:latest


    - name: app run
      run: |
        docker run -it ghcr.io/dochimcifgi625fwxczwnjqow81a001:latest

        
        
